spring:
  application:
    name: catalog-service
  cloud:
    config:
      enabled: false
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  lifecycle:
    timeout-per-shutdown-phase: 15s

management:
  endpoints:
    web:
      exposure:
        include: refresh

polar:
  greeting: Welcome to the local book catalog!

server:
  shutdown: graceful