spring:
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 10000
      fail-fast: true
      retry:
        max-attempts: 5
        initial-interval: 1000
        max-interval: 5000
        multiplier: 1.1
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: refresh