version: "3.8"
services:

  catalog-service:
    depends_on:
      - polar-postgres-catalog
    image: "catalog-service"
    container_name: "catalog-service"
    ports:
      - "8080:8080"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
      - SPRING_PROFILES_ACTIVE=testdata
      - SPRING_CLOUD_CONFIG_ENABLED=false

  polar-postgres:
    image: "postgres:14.4"
    container_name: "polar-postgres-catalog"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=polardb_catalog